.PHONY: clean

1:
	@chmod 755 ./1/.
	@pyhton 1.py

pointerlist:
	@chmod 755 .
	@python plisttest.py

arraylist:
	@chmod 755 .
	@python alisttest.py

pointerstack:
	@chmod 755 .
	@python pstacktest.py

arraystack:
	@chmod 755 .
	@pyhton astacktest.py

clean:
	@\rm -f *.pyc
