.PHONY: clean

pointerqueue:
	@chmod 755 ./1/
	@python ./1/pointerqueue.py

loctree:
	@chmod 755 ./2-3-9/
	@python ./2-3-9/loctree.py

lcrstree:
	@chmod 755 ./2-3-9/
	@python ./2-3-9/lcrstree.py

timing:
	@chmod 755 ./2-3-9/
	@python ./2-3-9/timing.py

huffman:
	@chmod 755 ./2-3-9/
	@python ./2-3-9/huffman.py

mergelists:
	@chmod 755 ./4/
	@python ./4/mergelists.py

preorder:
	@chmod 755 ./8/
	@python ./4/preorder.py "+ + 1 * 2 3 4"

postorder:
	@chmod 755 ./8/
	@python ./4/postorder.py "1 2 3 * +"

clean:
	@\rm -f *.pyc
