echo "MAKEFILE FOR ASSIGNMENT 1 for CS260 DATA STRUCTURES AND ALGOS"
echo "by Abir Razzak"
echo "Please read over the README file(s) for additional info and comments"

echo 
echo 
echo 

echo "****RUNNING POINTERS TIMING****"
python timing.py
echo "****RUNNING POINTERS TEST****"
python pointertest.py


find . -name "*.pyc" -type f -delete
find . -name "*.out" -type f -delete
find . -name "*.h.sch" -type f -delete